server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 15aabc01473d28088248674f31d23b45
  goto-domain:
    white-list:
      enable: true
      names: '菜鸟教程，知乎，必应，bilibili，百度贴吧'
      details:
        - runoob.com
        - zhihu.com
        - bing.com
        - cn.bing.com
        - tieba.baidu.com
        - bilibili.com